main1:
	g++ -c car.cpp -o car.o
	g++ -c ambulance.cpp -o ambulance.o
	g++ -c main.cpp -o main.o
	g++ car.o main.o ambulance.o
	rm *.o

main2:
	g++ -c car.cpp -o car.o
	g++ -c ambulance.cpp -o ambulance.o
	g++ -c main.cpp -o main.o
	g++ car.o main.o ambulance.o
	rm *.o
